/**
 * Bake the land mask that `dotglobe/land` ships, from Natural Earth 110m countries.
 *
 * Each cell of an equirectangular grid is tested against the country polygons. The rows are
 * then XORed with the row above, packed to bits, and gzipped. Coastlines change little from
 * one row to the next, so the XOR leaves mostly zeros and the gzip stays small. The browser
 * undoes it with DecompressionStream, which needs no code of ours.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { feature } from 'topojson-client';
import { countryIndex } from '../dist/dotglobe.js';

const [cols, rows] = [Number(process.argv[2] ?? 1024), Number(process.argv[3] ?? 512)];
const topo = JSON.parse(readFileSync('demo/countries-110m.json', 'utf8'));
const geometries = feature(topo, topo.objects.countries).features
  .map((f) => f.geometry).filter((g) => g && (g.type === 'Polygon' || g.type === 'MultiPolygon'));
const index = countryIndex(geometries);

const bits = new Uint8Array(Math.ceil(cols / 8) * rows);
const stride = Math.ceil(cols / 8);
let land = 0;
const prev = new Uint8Array(cols);
const cur = new Uint8Array(cols);
for (let y = 0; y < rows; y++) {
  const lat = 90 - ((y + 0.5) / rows) * 180;
  for (let x = 0; x < cols; x++) {
    const lng = ((x + 0.5) / cols) * 360 - 180;
    cur[x] = index.locate(lat, lng) >= 0 ? 1 : 0;
    land += cur[x];
    if (cur[x] ^ prev[x]) bits[y * stride + (x >> 3)] |= 128 >> (x & 7);
  }
  prev.set(cur);
}
const gz = gzipSync(bits, { level: 9 });
const b64 = gz.toString('base64');
console.log(`${cols}x${rows}: land ${(100 * land / (cols * rows)).toFixed(1)} %, packed ${bits.length} B, gzip ${gz.length} B, base64 ${b64.length} B`);
if (process.argv[4] === 'write') {
  writeFileSync('src/land.data.ts', `// Generated by scripts/bake-land.mjs from Natural Earth 110m. Do not edit.\nexport const WIDTH = ${cols};\nexport const HEIGHT = ${rows};\nexport const DATA = '${b64}';\n`);
  console.log('wrote src/land.data.ts');
}
